theme: jekyll-theme-slate
title: [Ruy Freitas Reis]
description: [ğŸ‘¨ğŸ»â€ğŸ“PhD in Computational Modeling 

ğŸ‘¨ğŸ»â€ğŸ’» Computational Engineer and Computer Scientist 

ğŸ‘¨ğŸ»â€ğŸ« Adjunct Professor and Researcher at UFJF]
github:
  is_project_page: false
